利用可能曜日のバリデーター
codeforjapan/OpenDataTools pull request #114
Opened 2022-10-15 14:48 UTC by champierre

#13

2022-10-17 11:59 UTC, champierre commented
rebase して vercel へのデプロイで出ていたエラーもなくしました。

2022-10-17 15:17 UTC, kota-yata requested changes

2022-10-17 15:17 UTC, kota-yata commented on datamanager/nodejs/items/validator/dow.ts
> +    if (typeof data != 'string') {
念のため厳密等価演算子に変更をお願いします

2022-10-17 23:17 UTC, champierre commented on datamanager/nodejs/items/validator/dow.ts
> +    if (typeof data != 'string') {
修正しました。あわせて他のテストの同様の箇所も修正しておきました。

2022-10-17 23:17 UTC, champierre commented on datamanager/nodejs/items/validator/dow.ts
> +    const matched = data.match(/^月?火?水?木?金?土?日?$/);
@kota-yata 曜日の漢字以外の文字が使われている場合と順番が正しくない場合とでエラーを分けました。

2022-10-18 14:03 UTC, kota-yata approved these changes
LGTM 🈂️

2022-10-18 23:27 UTC, merged