セルデータ単位の編集を電話番号と都道府県又は市区町村コードにて実装
codeforjapan/OpenDataTools pull request #87
Opened 2022-10-05 14:06 UTC by yu23ki14

2022-10-05 16:02 UTC, kaizumaki commented
lintエラーが出ているのですが、たぶん最新のmainをpullすれば通ると思います。どうでしょうね？

2022-10-06 00:29 UTC, kaizumaki requested changes
１点コメントしました！

2022-10-06 00:29 UTC, kaizumaki commented on webclient/src/components/Editor/DataEditorMain.tsx
> +import { Input } from '@chakra-ui/input';
ここは `OstInput` でいけますか？元の実装で `OstInput` にしていたので。。

2022-10-06 00:37 UTC, yu23ki14 commented on webclient/src/components/Editor/DataEditorMain.tsx
> +import { Input } from '@chakra-ui/input';
お、残骸がのこっていましたね

2022-10-06 00:42 UTC, kaizumaki approved these changes
ありがとうございます！LGTMです！

2022-10-06 00:43 UTC, merged