CSVインポート画面のスタイリング
codeforjapan/OpenDataTools pull request #98
Opened 2022-10-10 11:19 UTC by Murayu0225

- close #79 

![スクリーンショット 2022-10-10 20 18 07](https://user-images.githubusercontent.com/37988559/194854622-8b025963-0184-43ed-b167-f0f5c0f3c3b3.png)

![スクリーンショット 2022-10-10 20 18 16](https://user-images.githubusercontent.com/37988559/194854566-3cdc3529-e13f-4f4d-951f-4a65d4c40f08.png)

2022-10-10 12:28 UTC, kaizumaki requested changes
PRありがとうございます！
細かい点で恐縮なのですが、３点Suggested changeしたのでご検討ください...！ 🙏

2022-10-10 12:28 UTC, kaizumaki commented on webclient/src/features/upload/routes/FileUpload.tsx
> +          </Box>
```suggestion
          <Text
            display="inline-block"
            bg="information.bg.active"
            borderRadius="3em"
            px={8}
            py={2}
          >
            次のステップに進むと検証前に必要な自動変換がはじまります
          </Text>
```

2022-10-10 12:28 UTC, kaizumaki commented on webclient/src/features/upload/routes/FileUpload.tsx
> +          ? `CSVファイルをアップロードしてください`
```suggestion
          ? 'CSVファイルをアップロードしてください'
```

2022-10-10 12:28 UTC, kaizumaki commented on webclient/src/features/upload/routes/FileUpload.tsx
> +      pageTitle={'CSVアップロード'}
```suggestion
      pageTitle="CSVアップロード"
```

2022-10-10 12:54 UTC, kaizumaki commented on webclient/src/features/upload/routes/FileUpload.tsx
> +import { Avatar, Box, Center, cssVar, Flex, Input, InputGroup } from '@chakra-ui/react';
```suggestion
import { Avatar, Box, Center, Flex, Input, InputGroup, Text } from '@chakra-ui/react';
```

2022-10-10 23:21 UTC, kaizumaki approved these changes
私のほうでSuggested changeを取り込ませていただきました 🙇 
これでマージとしたいと思います！もろもろありがとうございます！

2022-10-10 23:21 UTC, merged

2022-10-11 03:25 UTC, Murayu0225 commented
遅くなりすみません！
ありがとうございます